---
galaxy_info:
  author: z
  description: security configure for CentOS/RedHat
  company:
  license: license (BSD, MIT)
  min_ansible_version: 1.7
  platforms:
  - name: EL
    versions:
    - 6
    - 7
  categories:
  - system
dependencies: []
