---
- name: apply conf to all nodes
  hosts: all
  roles:
#    - scathatheworm.security-settings
    - role: logrotate
      logrotate_backlog_size: 52
    - role: packages
      tags: pkgs
    - role: filedefs
      tags: files
    - role: franklinkim.sudo
      vars:
        sudo_users:
          - name: 'zaphod'
            nopasswd: yes
