---
- name: apply conf to all nodes
  hosts: all
  roles:
#    - scathatheworm.security-settings
    - ansible-role-ntpd
    - role: logrotate
      logrotate_backlog_size: 52
    - role: packages
    - role: franklinkim.sudo
      vars:
        sudo_users:
          - name: 'stuart'
            nopasswd: yes
