---
- name: Ensure that the cronie package is installed
  tags: cronie
  apt:
    name: cronie
    state: present
    update_cache: yes
  register: cronie_yum

- block:
    - name: Applying cronie hourly and sysconfig configurations
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dst }}"
        owner: root
        group: root
        mode: "{{ item.mode }}"
      notify: restart crond
      with_items:
        - { src: 0hourly.j2, dst: /etc/cron.d/0hourly, mode: '0644' }
        - { src: crond.sysconfig.j2, dst: /etc/sysconfig/crond, mode: '0600' }

    - name: Applying cron.allow configuration (if applicable)
      template:
        src: cron.allow.j2
        dest: /etc/cron.allow
        owner: root
        group: root
        mode: 0600
      notify: restart crond
      when: cronie_allow is defined

    - name: Applying cron.deny configuration (if applicable)
      template:
        src: cron.deny.j2
        dest: /etc/cron.deny
        owner: root
        group: root
        mode: 0600
      notify: restart crond
      when: cronie_deny is defined

    - name: Applying cronie job configurations
      template:
        src: cronie.j2
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0644
      notify: restart crond
      with_items: "{{ cronie_jobs }}"
      when: 
        - cronie_jobs is defined
        - item.dest is defined
        - item.jobs is defined

    - name: Enable and start the crond service
      service:
        enabled: yes
        name: crond
        state: started
  tags: cronie
  when: cronie_yum|success
...
