---
galaxy_info:
  author: Felix Archambault
  description: Ansible role to install packages on a host
  license: MIT
  min_ansible_version: 2.5
  platforms:
    - name: EL
      versions:
        - 6
        - 7
    - name: Fedora
      versions:
        - 20
        - 21
        - 22
        - 23
        - 24
        - 25
        - 26
    - name: Ubuntu
      versions:
        - trusty
        - utopic
        - vivid
        - wily
        - xenial
        - artful
        - bionic
    - name: Debian
      versions:
        - stretch
        - wheezy

  galaxy_tags:
    - system
    - packages

dependencies: []
